# Generated by infrachart. Review before applying.
#
# Resource bodies carry only the parameters the chart models. Run
# `tofu validate` to see what each provider still requires.
#
# Resource names come from asset IDs, never display names: a name-derived
# address would make renaming an asset destroy and recreate it.
#
# Removing an account also removes its provider block, and OpenTofu cannot
# destroy a resource whose provider is gone. Empty the account of assets,
# apply, then remove the account.
#
# Ports in these rules are always the DESTINATION port — the port being
# connected to. On AWS, from_port and to_port are the low and high bounds of
# one range, not a source and a destination: from_port = 443, to_port = 443
# is the range 443-443. Source ports are never constrained, because they are
# ephemeral, and every firewall here is stateful — return traffic needs no
# rule of its own.

terraform {
  required_providers {
    aws          = { source = "hashicorp/aws" }
    azurerm      = { source = "hashicorp/azurerm" }
    digitalocean = { source = "digitalocean/digitalocean" }
    google       = { source = "hashicorp/google" }
  }
}

# Resolved SSH keys: per resource, then per account, then deployment-wide.
locals {
  asset_aws_ec2_ssh_key          = coalesce(var.acc_aws_ssh_public_key, var.ssh_public_key, "")
  asset_azure_vm_ssh_key         = coalesce(var.acc_azure_ssh_public_key, var.ssh_public_key, "")
  asset_digitalocean_drp_ssh_key = coalesce(var.acc_digitalocean_ssh_public_key, var.ssh_public_key, "")
  asset_gcp_gce_ssh_key          = coalesce(var.acc_gcp_ssh_public_key, var.ssh_public_key, "")
}

# ---------------------------------------------------------------
# AWS (AWS)
# ---------------------------------------------------------------

# Credentials come from the environment or your provider profile.
provider "aws" {
  alias  = "acc_aws"
  region = var.acc_aws_region
}

variable "acc_aws_region" {
  description = "Region for AWS"
  type        = string
  default     = "eu-west-2"
}

data "aws_availability_zones" "acc_aws" {
  provider = aws.acc_aws
  state    = "available"
}

resource "aws_vpc" "acc_aws" {
  provider   = aws.acc_aws
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "acc_aws" {
  provider          = aws.acc_aws
  vpc_id            = aws_vpc.acc_aws.id
  cidr_block        = "10.0.1.0/24"
  availability_zone = data.aws_availability_zones.acc_aws.names[0]
}

resource "aws_subnet" "acc_aws_b" {
  provider          = aws.acc_aws
  vpc_id            = aws_vpc.acc_aws.id
  cidr_block        = "10.0.2.0/24"
  availability_zone = data.aws_availability_zones.acc_aws.names[1]
}

resource "aws_internet_gateway" "acc_aws" {
  provider = aws.acc_aws
  vpc_id   = aws_vpc.acc_aws.id
}

resource "aws_route_table" "acc_aws" {
  provider = aws.acc_aws
  vpc_id   = aws_vpc.acc_aws.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.acc_aws.id
  }
}

resource "aws_route_table_association" "acc_aws" {
  provider       = aws.acc_aws
  subnet_id      = aws_subnet.acc_aws.id
  route_table_id = aws_route_table.acc_aws.id
}

resource "aws_route_table_association" "acc_aws_b" {
  provider       = aws.acc_aws
  subnet_id      = aws_subnet.acc_aws_b.id
  route_table_id = aws_route_table.acc_aws.id
}

# AWS → EC2 instance
resource "aws_instance" "asset_aws_ec2" {
  provider                    = aws.acc_aws
  tags                        = { Name = "EC2 instance" }
  instance_type               = "t3.micro"
  associate_public_ip_address = false
  monitoring                  = false
  subnet_id                   = aws_subnet.acc_aws.id
  key_name                    = one(aws_key_pair.asset_aws_ec2_key[*].key_name)
  ami                         = data.aws_ssm_parameter.asset_aws_ec2_ami.value
  metadata_options {
    http_tokens = "required"
  }
  root_block_device {
    volume_size = 20
    encrypted   = true
  }
}

# EC2 instance requires this
resource "aws_key_pair" "asset_aws_ec2_key" {
  count      = local.asset_aws_ec2_ssh_key != "" ? 1 : 0
  provider   = aws.acc_aws
  key_name   = "asset-aws-ec2"
  public_key = local.asset_aws_ec2_ssh_key
}

# EC2 instance resolves its image here, so the id is right for the account's region
data "aws_ssm_parameter" "asset_aws_ec2_ami" {
  provider = aws.acc_aws
  name     = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}

# AWS → Lambda
resource "aws_lambda_function" "asset_aws_btype" {
  provider      = aws.acc_aws
  tags          = { Name = "Lambda" }
  runtime       = "nodejs20.x"
  handler       = "index.handler"
  memory_size   = 128
  timeout       = 3
  function_name = "asset-aws-btype"
  filename      = var.asset_aws_btype_package
  role          = aws_iam_role.asset_aws_btype_role.arn
}

# Lambda requires this
resource "aws_iam_role" "asset_aws_btype_role" {
  provider = aws.acc_aws
  name     = "asset-aws-btype-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Action    = "sts:AssumeRole"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })
}

# AWS → RDS database
resource "aws_db_instance" "asset_aws_rds" {
  provider                    = aws.acc_aws
  tags                        = { Name = "RDS database" }
  engine                      = "postgres"
  engine_version              = "16.3"
  instance_class              = "db.t3.micro"
  allocated_storage           = 20
  username                    = "dbadmin"
  storage_encrypted           = true
  publicly_accessible         = false
  auto_minor_version_upgrade  = true
  multi_az                    = false
  skip_final_snapshot         = true
  deletion_protection         = false
  backup_retention_period     = 0
  manage_master_user_password = true
  db_subnet_group_name        = aws_db_subnet_group.asset_aws_rds_subnets.name
}

# RDS database requires this
resource "aws_db_subnet_group" "asset_aws_rds_subnets" {
  provider   = aws.acc_aws
  name       = "asset-aws-rds"
  subnet_ids = [aws_subnet.acc_aws.id, aws_subnet.acc_aws_b.id]
}

# AWS → S3 bucket
resource "aws_s3_bucket" "asset_aws_s3" {
  provider      = aws.acc_aws
  tags          = { Name = "S3 bucket" }
  force_destroy = true
  bucket_prefix = "asset-aws-s3-"
}

# S3 bucket requires this
resource "aws_s3_bucket_public_access_block" "asset_aws_s3_public_access" {
  provider                = aws.acc_aws
  bucket                  = aws_s3_bucket.asset_aws_s3.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# S3 bucket requires this
resource "aws_s3_bucket_server_side_encryption_configuration" "asset_aws_s3_encryption" {
  provider = aws.acc_aws
  bucket   = aws_s3_bucket.asset_aws_s3.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# S3 bucket requires this
resource "aws_s3_bucket_versioning" "asset_aws_s3_versioning" {
  provider = aws.acc_aws
  bucket   = aws_s3_bucket.asset_aws_s3.id
  versioning_configuration {
    status = "Enabled"
  }
}

# AWS → Load balancer
resource "aws_lb" "asset_aws_alb" {
  provider                   = aws.acc_aws
  tags                       = { Name = "Load balancer" }
  internal                   = false
  load_balancer_type         = "application"
  drop_invalid_header_fields = true
  enable_deletion_protection = false
  subnets                    = [aws_subnet.acc_aws.id, aws_subnet.acc_aws_b.id]
}

# AWS → ECS service
resource "aws_ecs_service" "asset_aws_ecs" {
  provider        = aws.acc_aws
  tags            = { Name = "ECS service" }
  launch_type     = "FARGATE"
  desired_count   = 1
  name            = "asset-aws-ecs"
  cluster         = aws_ecs_cluster.asset_aws_ecs_cluster.id
  task_definition = aws_ecs_task_definition.asset_aws_ecs_task.arn
  network_configuration {
    subnets          = [aws_subnet.acc_aws.id]
    assign_public_ip = false
  }
}

# ECS service requires this
resource "aws_ecs_cluster" "asset_aws_ecs_cluster" {
  provider = aws.acc_aws
  name     = "asset-aws-ecs"
}

# ECS service requires this
resource "aws_ecs_task_definition" "asset_aws_ecs_task" {
  provider                 = aws.acc_aws
  family                   = "asset-aws-ecs"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"
  container_definitions = jsonencode([{
    name      = "app"
    image     = var.asset_aws_ecs_image
    essential = true
  }])
}

# AWS → CloudFront CDN
resource "aws_cloudfront_distribution" "asset_aws_cdn" {
  provider    = aws.acc_aws
  tags        = { Name = "CloudFront CDN" }
  price_class = "PriceClass_100"
  enabled     = true
  default_cache_behavior {
    viewer_protocol_policy = "redirect-to-https"
    default_ttl            = 3600
    target_origin_id       = "asset-aws-cdn-origin"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
  }
  origin {
    domain_name = var.asset_aws_cdn_origin_domain
    origin_id   = "asset-aws-cdn-origin"
  }
  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }
  viewer_certificate {
    cloudfront_default_certificate = true
  }
}

# ---------------------------------------------------------------
# Azure (Azure)
# ---------------------------------------------------------------

# Credentials come from the environment or your provider profile.
provider "azurerm" {
  alias = "acc_azure"
  features {
  }
}

variable "acc_azure_region" {
  description = "Region for Azure"
  type        = string
  default     = "uksouth"
}

resource "azurerm_resource_group" "acc_azure" {
  provider = azurerm.acc_azure
  name     = "acc_azure"
  location = var.acc_azure_region
}

resource "azurerm_virtual_network" "acc_azure" {
  provider            = azurerm.acc_azure
  name                = "acc_azure"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.acc_azure.location
  resource_group_name = azurerm_resource_group.acc_azure.name
}

resource "azurerm_subnet" "acc_azure" {
  provider             = azurerm.acc_azure
  name                 = "acc_azure"
  resource_group_name  = azurerm_resource_group.acc_azure.name
  virtual_network_name = azurerm_virtual_network.acc_azure.name
  address_prefixes     = ["10.0.1.0/24"]
}

# Azure → Virtual machine
resource "azurerm_linux_virtual_machine" "asset_azure_vm" {
  provider                        = azurerm.acc_azure
  tags                            = { Name = "Virtual machine" }
  size                            = "Standard_B2s"
  disable_password_authentication = true
  name                            = "asset-azure-vm"
  resource_group_name             = azurerm_resource_group.acc_azure.name
  location                        = azurerm_resource_group.acc_azure.location
  admin_username                  = "azureuser"
  network_interface_ids           = [azurerm_network_interface.asset_azure_vm_nic.id]
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }
  source_image_reference {
    publisher = "Canonical"
    offer     = "ubuntu-24_04-lts"
    sku       = "server"
    version   = "latest"
  }
  admin_ssh_key {
    username   = "azureuser"
    public_key = local.asset_azure_vm_ssh_key
  }
}

# Virtual machine requires this
resource "azurerm_network_interface" "asset_azure_vm_nic" {
  provider            = azurerm.acc_azure
  name                = "asset-azure-vm-nic"
  resource_group_name = azurerm_resource_group.acc_azure.name
  location            = azurerm_resource_group.acc_azure.location
  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.acc_azure.id
    private_ip_address_allocation = "Dynamic"
  }
}

# Azure → Function app
resource "azurerm_linux_function_app" "asset_azure_fn" {
  provider                   = azurerm.acc_azure
  tags                       = { Name = "Function app" }
  https_only                 = true
  name                       = "asset-azure-fn"
  resource_group_name        = azurerm_resource_group.acc_azure.name
  location                   = azurerm_resource_group.acc_azure.location
  storage_account_name       = azurerm_storage_account.asset_azure_fn_storage.name
  storage_account_access_key = azurerm_storage_account.asset_azure_fn_storage.primary_access_key
  service_plan_id            = azurerm_service_plan.asset_azure_fn_plan.id
  site_config {
  }
}

# Function app requires this
resource "azurerm_service_plan" "asset_azure_fn_plan" {
  provider            = azurerm.acc_azure
  name                = "asset-azure-fn-plan"
  resource_group_name = azurerm_resource_group.acc_azure.name
  location            = azurerm_resource_group.acc_azure.location
  os_type             = "Linux"
  sku_name            = "Y1"
}

# Function app requires this
resource "azurerm_storage_account" "asset_azure_fn_storage" {
  provider                 = azurerm.acc_azure
  name                     = substr(replace("asset_azure_fn", "_", ""), 0, 24)
  resource_group_name      = azurerm_resource_group.acc_azure.name
  location                 = azurerm_resource_group.acc_azure.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
}

# Azure → Blob storage
resource "azurerm_storage_account" "asset_azure_blb" {
  provider                        = azurerm.acc_azure
  tags                            = { Name = "Blob storage" }
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  https_traffic_only_enabled      = true
  min_tls_version                 = "TLS1_2"
  allow_nested_items_to_be_public = false
  public_network_access_enabled   = false
  name                            = substr(replace("asset_azure_blb", "_", ""), 0, 24)
  resource_group_name             = azurerm_resource_group.acc_azure.name
  location                        = azurerm_resource_group.acc_azure.location
}

# Azure → SQL database
resource "azurerm_mssql_database" "asset_azure_sql" {
  provider       = azurerm.acc_azure
  tags           = { Name = "SQL database" }
  sku_name       = "S0"
  max_size_gb    = 32
  zone_redundant = false
  name           = "asset-azure-sql"
  server_id      = azurerm_mssql_server.asset_azure_sql_server.id
}

# SQL database requires this
resource "azurerm_mssql_server" "asset_azure_sql_server" {
  provider                      = azurerm.acc_azure
  name                          = "asset-azure-sql-sql"
  resource_group_name           = azurerm_resource_group.acc_azure.name
  location                      = azurerm_resource_group.acc_azure.location
  version                       = "12.0"
  administrator_login           = "sqladmin"
  administrator_login_password  = var.asset_azure_sql_sql_password
  minimum_tls_version           = "1.2"
  public_network_access_enabled = false
}

# Azure → AKS cluster
resource "azurerm_kubernetes_cluster" "asset_azure_aks" {
  provider            = azurerm.acc_azure
  tags                = { Name = "AKS cluster" }
  kubernetes_version  = "1.30"
  name                = "asset-azure-aks"
  resource_group_name = azurerm_resource_group.acc_azure.name
  location            = azurerm_resource_group.acc_azure.location
  dns_prefix          = "asset-azure-aks"
  default_node_pool {
    node_count = 3
    vm_size    = "Standard_DS2_v2"
    name       = "default"
  }
  identity {
    type = "SystemAssigned"
  }
  node_provisioning_profile {
    mode = "Manual"
  }
}

# Azure → App gateway
resource "azurerm_application_gateway" "asset_azure_apg" {
  provider            = azurerm.acc_azure
  tags                = { Name = "App gateway" }
  name                = "asset-azure-apg"
  resource_group_name = azurerm_resource_group.acc_azure.name
  location            = azurerm_resource_group.acc_azure.location
  sku {
    capacity = 2
    name     = "Standard_v2"
    tier     = "Standard_v2"
  }
  gateway_ip_configuration {
    name      = "gateway-ip"
    subnet_id = azurerm_subnet.asset_azure_apg_subnet.id
  }
  frontend_port {
    name = "http"
    port = 80
  }
  frontend_ip_configuration {
    name                 = "frontend"
    public_ip_address_id = azurerm_public_ip.asset_azure_apg_pip.id
  }
  backend_address_pool {
    name = "backend"
  }
  backend_http_settings {
    name                  = "settings"
    cookie_based_affinity = "Disabled"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 60
  }
  http_listener {
    name                           = "listener"
    frontend_ip_configuration_name = "frontend"
    frontend_port_name             = "http"
    protocol                       = "Http"
  }
  request_routing_rule {
    name                       = "rule"
    priority                   = 1
    rule_type                  = "Basic"
    http_listener_name         = "listener"
    backend_address_pool_name  = "backend"
    backend_http_settings_name = "settings"
  }
}

# App gateway requires this
resource "azurerm_public_ip" "asset_azure_apg_pip" {
  provider            = azurerm.acc_azure
  name                = "asset-azure-apg-pip"
  resource_group_name = azurerm_resource_group.acc_azure.name
  location            = azurerm_resource_group.acc_azure.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

# App gateway requires this
resource "azurerm_subnet" "asset_azure_apg_subnet" {
  provider             = azurerm.acc_azure
  name                 = "asset-azure-apg-subnet"
  resource_group_name  = azurerm_resource_group.acc_azure.name
  virtual_network_name = azurerm_virtual_network.acc_azure.name
  address_prefixes     = ["10.0.3.0/24"]
}

# Azure → Azure CDN
resource "azurerm_cdn_endpoint" "asset_azure_cdn" {
  provider            = azurerm.acc_azure
  tags                = { Name = "Azure CDN" }
  is_https_allowed    = true
  is_http_allowed     = false
  name                = "asset-azure-cdn"
  resource_group_name = azurerm_resource_group.acc_azure.name
  location            = "global"
  profile_name        = azurerm_cdn_profile.asset_azure_cdn_profile.name
  origin {
    name      = "origin"
    host_name = var.asset_azure_cdn_origin_host
  }
}

# Azure CDN requires this
resource "azurerm_cdn_profile" "asset_azure_cdn_profile" {
  provider            = azurerm.acc_azure
  name                = "asset-azure-cdn-profile"
  resource_group_name = azurerm_resource_group.acc_azure.name
  location            = "global"
  sku                 = "Standard_Microsoft"
}

# ---------------------------------------------------------------
# DigitalOcean (DigitalOcean)
# ---------------------------------------------------------------

# Credentials come from the environment or your provider profile.
provider "digitalocean" {
  alias = "acc_digitalocean"
}

variable "acc_digitalocean_region" {
  description = "Region for DigitalOcean"
  type        = string
  default     = "lon1"
}

resource "digitalocean_vpc" "acc_digitalocean" {
  name   = "acc-digitalocean"
  region = var.acc_digitalocean_region
}

# DigitalOcean → Droplet
resource "digitalocean_droplet" "asset_digitalocean_drp" {
  provider   = digitalocean.acc_digitalocean
  name       = "asset-digitalocean-drp"
  size       = "s-1vcpu-1gb"
  image      = "ubuntu-24-04-x64"
  region     = "lon1"
  monitoring = true
  backups    = false
  vpc_uuid   = digitalocean_vpc.acc_digitalocean.id
  ssh_keys   = digitalocean_ssh_key.asset_digitalocean_drp_key[*].id
}

# Droplet requires this
resource "digitalocean_ssh_key" "asset_digitalocean_drp_key" {
  count      = local.asset_digitalocean_drp_ssh_key != "" ? 1 : 0
  provider   = digitalocean.acc_digitalocean
  name       = "asset-digitalocean-drp"
  public_key = local.asset_digitalocean_drp_ssh_key
}

# DigitalOcean → App platform
resource "digitalocean_app" "asset_digitalocean_app" {
  provider = digitalocean.acc_digitalocean
  spec {
    region = "lon"
    name   = "asset-digitalocean-app"
    service {
      instance_size_slug = "basic-xxs"
      instance_count     = 1
      name               = "web"
      image {
        registry_type = "DOCKER_HUB"
        repository    = "nginx"
        tag           = "latest"
      }
    }
  }
}

# DigitalOcean → Spaces bucket
resource "digitalocean_spaces_bucket" "asset_digitalocean_spc" {
  provider      = digitalocean.acc_digitalocean
  name          = "asset-digitalocean-spc"
  region        = "ams3"
  acl           = "private"
  force_destroy = true
}

# DigitalOcean → Managed DB
resource "digitalocean_database_cluster" "asset_digitalocean_db" {
  provider             = digitalocean.acc_digitalocean
  name                 = "asset-digitalocean-db"
  engine               = "pg"
  version              = "16"
  size                 = "db-s-1vcpu-1gb"
  node_count           = 1
  region               = "lon1"
  private_network_uuid = digitalocean_vpc.acc_digitalocean.id
}

# DigitalOcean → Kubernetes
resource "digitalocean_kubernetes_cluster" "asset_digitalocean_k8s" {
  provider = digitalocean.acc_digitalocean
  name     = "asset-digitalocean-k8s"
  region   = "lon1"
  version  = "1.31.1-do.4"
  vpc_uuid = digitalocean_vpc.acc_digitalocean.id
  node_pool {
    size       = "s-2vcpu-4gb"
    node_count = 3
    name       = "default"
  }
}

# DigitalOcean → Load balancer
resource "digitalocean_loadbalancer" "asset_digitalocean_lb" {
  provider               = digitalocean.acc_digitalocean
  name                   = "asset-digitalocean-lb"
  region                 = "lon1"
  size                   = "lb-small"
  redirect_http_to_https = true
  vpc_uuid               = digitalocean_vpc.acc_digitalocean.id
  forwarding_rule {
    entry_port      = 80
    entry_protocol  = "http"
    target_port     = 80
    target_protocol = "http"
  }
}

# DigitalOcean → CDN endpoint
resource "digitalocean_cdn" "asset_digitalocean_cdn" {
  provider      = digitalocean.acc_digitalocean
  ttl           = 3600
  custom_domain = ""
  origin        = digitalocean_spaces_bucket.asset_digitalocean_cdn_origin.bucket_domain_name
}

# CDN endpoint requires this
resource "digitalocean_spaces_bucket" "asset_digitalocean_cdn_origin" {
  provider      = digitalocean.acc_digitalocean
  name          = "asset-digitalocean-cdn-origin"
  region        = "ams3"
  acl           = "public-read"
  force_destroy = true
}

# ---------------------------------------------------------------
# GCP (GCP)
# ---------------------------------------------------------------

# Credentials come from the environment or your provider profile.
provider "google" {
  alias   = "acc_gcp"
  region  = var.acc_gcp_region
  project = var.acc_gcp_project
}

variable "acc_gcp_region" {
  description = "Region for GCP"
  type        = string
  default     = "europe-west2"
}

resource "google_compute_network" "acc_gcp" {
  provider                = google.acc_gcp
  name                    = "acc-gcp"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "acc_gcp" {
  provider      = google.acc_gcp
  name          = "acc-gcp"
  ip_cidr_range = "10.0.1.0/24"
  region        = var.acc_gcp_region
  network       = google_compute_network.acc_gcp.id
}

# GCP → Compute engine
resource "google_compute_instance" "asset_gcp_gce" {
  provider     = google.acc_gcp
  name         = "asset-gcp-gce"
  machine_type = "e2-medium"
  zone         = "europe-west2-a"
  metadata     = local.asset_gcp_gce_ssh_key != "" ? { ssh-keys = "ansible:${local.asset_gcp_gce_ssh_key}" } : {}
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 10
    }
  }
  shielded_instance_config {
    enable_secure_boot = true
    enable_vtpm        = true
  }
  network_interface {
    subnetwork = google_compute_subnetwork.acc_gcp.id
  }
}

# GCP → Cloud function
resource "google_cloudfunctions2_function" "asset_gcp_gcf" {
  provider = google.acc_gcp
  name     = "asset-gcp-gcf"
  location = var.acc_gcp_region
  build_config {
    runtime     = "nodejs20"
    entry_point = "handler"
    source {
      storage_source {
        bucket = google_storage_bucket.asset_gcp_gcf_src.name
        object = google_storage_bucket_object.asset_gcp_gcf_srcobj.name
      }
    }
  }
  service_config {
    available_memory = "256M"
    ingress_settings = "ALLOW_INTERNAL_ONLY"
  }
}

# Cloud function requires this
resource "google_storage_bucket" "asset_gcp_gcf_src" {
  provider                    = google.acc_gcp
  name                        = "asset-gcp-gcf-src"
  location                    = "EU"
  uniform_bucket_level_access = true
  force_destroy               = true
}

# Cloud function requires this
resource "google_storage_bucket_object" "asset_gcp_gcf_srcobj" {
  provider = google.acc_gcp
  name     = "source.zip"
  bucket   = google_storage_bucket.asset_gcp_gcf_src.name
  source   = var.asset_gcp_gcf_source
}

# GCP → Cloud storage
resource "google_storage_bucket" "asset_gcp_gcs" {
  provider                    = google.acc_gcp
  name                        = "asset-gcp-gcs"
  location                    = "EU"
  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
  public_access_prevention    = "enforced"
  force_destroy               = true
}

# GCP → Cloud SQL
resource "google_sql_database_instance" "asset_gcp_csql" {
  provider            = google.acc_gcp
  name                = "asset-gcp-csql"
  database_version    = "POSTGRES_16"
  deletion_protection = false
  region              = var.acc_gcp_region
  settings {
    tier              = "db-f1-micro"
    availability_type = "ZONAL"
    ip_configuration {
      ssl_mode = "ENCRYPTED_ONLY"
    }
    backup_configuration {
      enabled = true
    }
  }
}

# GCP → GKE cluster
resource "google_container_cluster" "asset_gcp_gke" {
  provider                 = google.acc_gcp
  name                     = "asset-gcp-gke"
  deletion_protection      = false
  location                 = var.acc_gcp_region
  remove_default_node_pool = true
  initial_node_count       = 1
  network                  = google_compute_network.acc_gcp.id
  subnetwork               = google_compute_subnetwork.acc_gcp.id
  workload_identity_config {
    workload_pool = "${var.acc_gcp_project}.svc.id.goog"
  }
}

# GKE cluster requires this
resource "google_container_node_pool" "asset_gcp_gke_nodes" {
  provider   = google.acc_gcp
  name       = "asset-gcp-gke-nodes"
  cluster    = google_container_cluster.asset_gcp_gke.id
  node_count = 3
  node_config {
    machine_type = "e2-medium"
    shielded_instance_config {
      enable_secure_boot = true
    }
  }
}

# GCP → Cloud CDN
resource "google_compute_backend_bucket" "asset_gcp_cdn" {
  provider    = google.acc_gcp
  name        = "asset-gcp-cdn"
  enable_cdn  = true
  bucket_name = google_storage_bucket.asset_gcp_cdn_bucket.name
  cdn_policy {
    cache_mode = "CACHE_ALL_STATIC"
  }
}

# Cloud CDN requires this
resource "google_storage_bucket" "asset_gcp_cdn_bucket" {
  provider                    = google.acc_gcp
  name                        = "asset-gcp-cdn-origin"
  location                    = "EU"
  uniform_bucket_level_access = true
  force_destroy               = true
}

# Values the chart cannot supply. Sensitive ones have no default, so
# `tofu plan` prompts for them rather than storing a secret here.

variable "ssh_public_key" {
  description = "SSH public key for every Ansible host. export TF_VAR_ssh_public_key=\"$(cat ~/.ssh/id_ed25519.pub)\""
  type        = string
  default     = ""
}

variable "acc_aws_ssh_public_key" {
  description = "SSH public key for Ansible hosts in AWS, overriding the deployment key"
  type        = string
  default     = ""
}

variable "acc_azure_ssh_public_key" {
  description = "SSH public key for Ansible hosts in Azure, overriding the deployment key"
  type        = string
  default     = ""
}

variable "acc_digitalocean_ssh_public_key" {
  description = "SSH public key for Ansible hosts in DigitalOcean, overriding the deployment key"
  type        = string
  default     = ""
}

variable "acc_gcp_ssh_public_key" {
  description = "SSH public key for Ansible hosts in GCP, overriding the deployment key"
  type        = string
  default     = ""
}

variable "asset_aws_btype_package" {
  description = "Path to the deployment package zip"
  type        = string
  default     = "lambda.zip"
}

variable "asset_aws_ecs_image" {
  description = "Container image for the service"
  type        = string
  default     = "public.ecr.aws/nginx/nginx:latest"
}

variable "asset_aws_cdn_origin_domain" {
  description = "Origin the distribution fetches from"
  type        = string
  default     = "origin.example.com"
}

variable "asset_azure_sql_sql_password" {
  description = "SQL server administrator password"
  type        = string
  sensitive   = true
}

variable "asset_azure_cdn_origin_host" {
  description = "Origin host the CDN fetches from"
  type        = string
  default     = "origin.example.com"
}

variable "acc_gcp_project" {
  description = "GCP project ID"
  type        = string
  default     = "my-project"
}

variable "asset_gcp_gcf_source" {
  description = "Path to the function source zip"
  type        = string
  default     = "function.zip"
}
