package tofu

import (
	"fmt"
	"strings"

	"infrachart/internal/catalog"
	"infrachart/internal/model"
)

// Generate renders a chart as OpenTofu configuration, and returns the things the
// user must act on alongside it.
//
// Run model.Validate and model.Normalise first. Output is deterministic: every
// loop walks a slice in order, never a map.
func Generate(s model.Session) (string, []string) {
	report := Classify(s)
	w := &writer{}

	// The inventory is resolved once: what it contains decides both whether the
	// local provider is required and whether the resource is emitted, and when
	// those were computed separately the only thing keeping them honest was a
	// panic comparing them.
	groups, hosts := inventory(s)

	header(w)
	requiredProviders(w, s, featureProviders(groups))

	// Rules are accumulated per account and rendered after the resources, because
	// DigitalOcean needs all of an asset's rules in one resource.
	firewalls := map[string]firewall{}
	for _, acc := range s.Accounts {
		if fw := newFirewall(acc.Provider); fw != nil {
			firewalls[acc.ID] = fw
		}
	}
	rules := dedupeRules(report, firewalls)
	for _, k := range rules {
		firewalls[k.owner].add(k.rule)
	}

	guarded := guardedAssets(rules)
	vars := newVarSet()
	renderKeyLocals(w, s)
	// The key variables exist only where something references them, so a chart
	// with no SSH key wiring is not asked for a key it has no use for.
	for _, acc := range s.Accounts {
		for _, a := range acc.Assets {
			rt, ok := catalog.Type(acc.Provider, a.Code)
			if !ok || !usesSSHKey(rt, a) {
				continue
			}
			for _, d := range sshKeyVars(acc.ID, acc.Name) {
				vars.add(d)
			}
		}
	}

	for _, acc := range s.Accounts {
		p, ok := catalog.Get(acc.Provider)
		if !ok {
			continue
		}
		w.blank()
		w.line("# ---------------------------------------------------------------")
		w.line("# %s (%s)", acc.Name, p.Label)
		w.line("# ---------------------------------------------------------------")
		providerBlock(w, p, acc, vars)
		scaffold(w, acc.Provider, acc.ID)
		for _, a := range acc.Assets {
			assetResource(w, p, acc, a, guarded[a.ID], vars)
		}
		if fw := firewalls[acc.ID]; fw != nil {
			fw.render(w, acc)
		}
	}

	if lists := prefixLists(report); len(lists) > 0 {
		w.blank()
		w.line("# Managed prefix lists, so a CDN can reach its origin without a CIDR.")
		for _, l := range lists {
			w.blank()
			w.block(fmt.Sprintf("data %q %q", "aws_ec2_managed_prefix_list", prefixListName(l)), func() {
				w.arg("name", quote(l))
			})
		}
	}

	renderInventory(w, groups, hosts)

	vars.render(w)
	externalIPs(w, s)
	attachmentGaps(w, s, guarded)
	notes(w, report)

	warnings := append(report.Warnings(), ansibleWarnings(s, report)...)
	warnings = append(warnings, unreachableWarnings(report)...)
	warnings = append(warnings, accountSettingWarnings(s)...)
	return w.String(), append(warnings, blankChoiceWarnings(s)...)
}

func header(w *writer) {
	w.line("# Generated by infrachart. Review before applying.")
	w.line("#")
	w.line("# Resource bodies carry only the parameters the chart models. Run")
	w.line("# `tofu validate` to see what each provider still requires.")
	w.line("#")
	w.line("# Resource names come from asset IDs, never display names: a name-derived")
	w.line("# address would make renaming an asset destroy and recreate it.")
	w.line("#")
	w.line("# Removing an account also removes its provider block, and OpenTofu cannot")
	w.line("# destroy a resource whose provider is gone. Empty the account of assets,")
	w.line("# apply, then remove the account.")
	w.line("#")
	w.line("# Ports in these rules are always the DESTINATION port — the port being")
	w.line("# connected to. On AWS, from_port and to_port are the low and high bounds of")
	w.line("# one range, not a source and a destination: from_port = 443, to_port = 443")
	w.line("# is the range 443-443. Source ports are never constrained, because they are")
	w.line("# ephemeral, and every firewall here is stateful — return traffic needs no")
	w.line("# rule of its own.")
}

// requiredProviders declares only the providers the chart actually uses, so a
// chart with no Azure in it does not demand Azure credentials.
// featureProviders are providers a chart never mentions but a feature needs. The
// inventory is a local_file, so an Ansible chart requires hashicorp/local even
// though no account is a "local" account.
func featureProviders(groups []string) []catalog.Provider {
	if len(groups) == 0 {
		return nil
	}
	return []catalog.Provider{{
		Key: "local", Label: "Local", TofuLocalName: "local", TofuSource: "hashicorp/local",
	}}
}

func requiredProviders(w *writer, s model.Session, extra []catalog.Provider) {
	inUse := map[string]bool{}
	for _, acc := range s.Accounts {
		inUse[acc.Provider] = true
	}
	// catalog.All() is sorted by key, so the block is stable regardless of the
	// order accounts happen to appear in the chart.
	var used []catalog.Provider
	for _, p := range catalog.All() {
		if inUse[p.Key] {
			used = append(used, p)
		}
	}
	used = append(used, extra...)
	if len(used) == 0 {
		return
	}
	w.blank()
	w.block("terraform", func() {
		w.block("required_providers", func() {
			for _, p := range used {
				w.arg(p.TofuLocalName, fmt.Sprintf("{ source = %s }", quote(p.TofuSource)))
			}
		})
	})
}

// providerBlock gives each account its own aliased provider configuration. This is
// what lets one configuration span accounts and clouds, which in turn is what
// makes a cross-account reference both resolve the address and order the apply.
func providerBlock(w *writer, p catalog.Provider, acc model.Account, vars *varSet) {
	w.blank()
	w.line("# Credentials come from the environment or your provider profile.")
	ctx := exprCtx{accountID: acc.ID}
	node := &blockNode{}
	node.add("", "alias", quote(acc.ID))
	for _, fx := range p.Config {
		addFixed(node, fx, ctx)
	}
	w.block(fmt.Sprintf("provider %q", p.TofuLocalName), func() { node.render(w) })
	for _, v := range p.Variables {
		def := expand(v.Default, ctx)
		// A value the chart carries becomes the variable's default, so it is
		// declared once and can still be overridden per apply with TF_VAR.
		if v.DefaultFromParam != "" {
			if got := p.AccountParam(acc.Params, v.DefaultFromParam); got != "" {
				def = quote(got)
			}
		}
		vars.add(varDecl{
			Name:        expand(v.Name, ctx),
			Description: v.Description,
			Default:     def,
			Sensitive:   v.Sensitive,
		})
	}
	w.blank()
	// The variable stays even though the chart now supplies a value, so a region
	// can still be overridden per apply with TF_VAR without editing the chart.
	w.block(fmt.Sprintf("variable %q", acc.ID+"_region"), func() {
		w.arg("description", quote("Region for "+acc.Name))
		w.arg("type", "string")
		w.arg("default", quote(p.Region(acc.Params)))
	})
}

// assetResource emits one asset, its fixed arguments and its companions. The
// resource name is the asset ID; the display name goes into tags or labels, which
// providers update in place, so renaming an asset never replaces infrastructure.
func assetResource(w *writer, p catalog.Provider, acc model.Account, a model.Asset, guarded bool, vars *varSet) {
	rt, ok := catalog.Type(acc.Provider, a.Code)
	if !ok {
		return
	}

	// Arguments are collected by block path first, then rendered in one pass, so
	// a nested argument does not have to know where it sits in the output.
	ctx := assetCtx(acc, a)
	root := &blockNode{}
	root.add("", "provider", p.TofuLocalName+"."+acc.ID)
	displayName(root, p, rt, a)

	// Arguments(), not Params: directives such as static_public_ip are not
	// arguments on any resource and would make the configuration invalid.
	for _, f := range rt.Arguments() {
		// Same gate as Fixed and Companions below. An argument in a block the
		// resource does not accept is a plan error, not a harmless extra.
		if !required(f.RequiresParam, f.RequiresValue, a) {
			continue
		}
		v := a.Params[f.ParamKey()]
		// An unwritten script is absence, not an empty script. Emitting it would
		// produce user_data = "" and, worse, base64encode("") on Azure.
		if f.Type == catalog.FieldScript && v == "" {
			continue
		}
		root.add(f.Block, f.Key, wrapped(f, v))
	}
	for _, fx := range rt.Fixed {
		if !required(fx.RequiresParam, fx.RequiresValue, a) {
			continue
		}
		addFixed(root, fx, ctx)
	}
	// A companion the parent never references would be dead HCL.
	for _, c := range rt.Companions {
		if !required(c.RequiresParam, c.RequiresValue, a) {
			continue
		}
		if c.ParentRef != "" {
			root.add("", c.ParentRef, expand(c.ParentExpr, ctx))
		}
	}
	if ansibleOn(&a) {
		keyPrecondition(root, acc, &a)
	}
	if guarded {
		attach(root, a, rt)
	}
	for _, v := range rt.Variables {
		vars.add(varDecl{
			Name:        expand(v.Name, ctx),
			Description: v.Description,
			Default:     expand(v.Default, ctx),
			Sensitive:   v.Sensitive,
		})
	}

	w.blank()
	w.line("# %s → %s", acc.Name, a.Name)
	w.block(fmt.Sprintf("resource %q %q", rt.TofuType, a.ID), func() { root.render(w) })

	for _, c := range rt.Companions {
		if !required(c.RequiresParam, c.RequiresValue, a) {
			continue
		}
		companionResource(w, p, acc, a, c)
	}
	staticAddress(w, p, acc, a, rt)
}

// companionResource emits a resource an asset cannot exist without. Named
// <assetID>_<suffix> so it inherits the guarantee that renaming an asset never
// moves a resource address.
func companionResource(w *writer, p catalog.Provider, acc model.Account, a model.Asset, c catalog.Companion) {
	name := a.ID + "_" + c.Suffix
	ctx := assetCtx(acc, a)
	node := &blockNode{}
	// count first: it is a meta-argument and reads as one at the top of the block.
	if c.Count != "" {
		node.add("", "count", expand(c.Count, ctx))
	}
	node.add("", "provider", p.TofuLocalName+"."+acc.ID)
	for _, fx := range c.Fixed {
		// Same gate as an asset's own fixed arguments. Without it a conditional
		// argument inside a companion was emitted unconditionally — which is how
		// Azure's public IP came out allocated but never attached.
		if !required(fx.RequiresParam, fx.RequiresValue, a) {
			continue
		}
		addFixed(node, fx, ctx)
	}
	w.blank()
	kind := "resource"
	if c.Data {
		// A data source is looked up, not created, so "requires this" would misread
		// as something the apply brings into existence.
		kind = "data"
		w.line("# %s resolves its image here, so the id is right for the account's region", a.Name)
	} else {
		w.line("# %s requires this", a.Name)
	}
	w.block(fmt.Sprintf("%s %q %q", kind, c.TofuType, name), func() { node.render(w) })
}

// assetCtx is what a catalog expression may refer to for one asset.
func assetCtx(acc model.Account, a model.Asset) exprCtx {
	return exprCtx{
		accountID: acc.ID,
		assetID:   a.ID,
		sshKey:    sshKeyLocal(a.ID),
		sshUser:   loginUser(&a),
	}
}

// ownedRule is one firewall rule and the account whose firewall carries it.
type ownedRule struct {
	owner string
	rule  fwRule
}

// dedupeRules collapses rules that describe the same permission.
//
// Two connections can mean the same thing — a host reaching the internet on 443,
// and reaching something that resolves to the same address on the same port — and
// so can one connection carrying a rule twice. Every provider funnels through
// here, so this is the one place that has to know.
//
// It is not a tidiness pass. AWS rejects the second identical rule outright with
// InvalidPermission.Duplicate, which fails the apply after some of the chart has
// already been created. `tofu validate` cannot see it, because the two resources
// are perfectly valid on their own and only collide at the API.
//
// Everything but the comment is the rule's identity; the comments are joined, so
// the output still says why a merged rule exists rather than silently naming one
// reason out of two.
func dedupeRules(report Report, firewalls map[string]firewall) []ownedRule {
	seen := map[ownedRule]int{}
	var out []ownedRule
	for _, f := range report.Flows {
		for _, o := range f.Outcomes {
			for _, r := range fwRulesFor(f, o) {
				owner := ruleOwner(f, r)
				if fw := firewalls[owner]; fw == nil {
					continue
				}
				key := ownedRule{owner, r}
				key.rule.Comment = ""
				if i, ok := seen[key]; ok {
					out[i].rule.Comment = mergeComments(out[i].rule.Comment, r.Comment)
					continue
				}
				seen[key] = len(out)
				out = append(out, ownedRule{owner, r})
			}
		}
	}
	return out
}

// mergeComments joins the reasons for a merged rule, dropping a repeat rather than
// saying the same thing twice.
func mergeComments(existing, add string) string {
	if add == "" || existing == add || strings.Contains(existing, add) {
		return existing
	}
	if existing == "" {
		return add
	}
	return existing + "; also " + add
}

// required reports whether a gated argument, fixed value or companion applies to
// this asset. catalog.GateOpen is the definition; the drawer reads the same one.
func required(param, value string, a model.Asset) bool {
	return catalog.GateOpen(param, value, a.Params)
}

// wrapped renders a param value, applying the type's Wrap expression when it has
// one. Azure's custom_data is the reason: it takes base64 where every other cloud
// takes a plain string.
func wrapped(f catalog.ParamField, v any) string {
	rendered := value(v)
	if f.Wrap == "" {
		return rendered
	}
	return fmt.Sprintf(f.Wrap, rendered)
}

// guardedAssets is the set of assets that ended up with at least one firewall
// rule, and therefore need the rule attached to them.
//
// It reads the rules that were actually emitted rather than walking the report a
// second time. The two loops were identical except that this one counted rules
// whose account has no firewall, which nothing emits.
func guardedAssets(rules []ownedRule) map[string]bool {
	out := map[string]bool{}
	for _, r := range rules {
		out[r.rule.Asset] = true
	}
	return out
}

// attach wires an asset to the firewall that protects it. Without this the rules
// exist but govern nothing — the output would look complete and do nothing.
//
// DigitalOcean needs no entry here: its firewall resource names the droplet
// directly, so attachment is inherent.
//
// Azure is handled in the firewall emitter instead: a security group attaches to a
// network interface there, not to the machine. attachmentGaps() still names every
// asset that nothing wires up, so the output never pretends to be complete.
func attach(n *blockNode, a model.Asset, rt catalog.ResourceType) {
	if block, key, expr, ok := attachArg(a, rt); ok {
		n.add(block, key, expr)
	}
}

// attachArg is the argument an asset uses to name its own firewall, and the
// expression to write into it.
//
// This is the only list of which types can be wired, and attached() reads it too
// — there used to be a second copy in attachmentGaps(), which meant adding a type
// here and forgetting there printed "attach its firewall yourself" about
// something that was already attached.
func attachArg(a model.Asset, rt catalog.ResourceType) (block, key, expr string, ok bool) {
	sg := fmt.Sprintf("[aws_security_group.%s.id]", a.ID)
	switch rt.TofuType {
	case "aws_instance", "aws_db_instance":
		return "", "vpc_security_group_ids", sg, true
	case "aws_lb":
		return "", "security_groups", sg, true
	case "aws_ecs_service":
		// A Fargate service takes its security groups inside the network block.
		return "network_configuration", "security_groups", sg, true
	case "google_compute_instance":
		// GCP firewall rules select instances by network tag rather than by group.
		return "", "tags", fmt.Sprintf("[%s]", quote(dashed(a.ID))), true
	}
	return "", "", "", false
}

// attached reports whether anything at all wires this type to a firewall, in
// either direction: the resource naming its firewall, or the firewall naming the
// resource.
func attached(a model.Asset, rt catalog.ResourceType) bool {
	_, _, _, ok := attachArg(a, rt)
	return ok || rt.FirewallRef != ""
}

// displayName records the chart's label on the resource without letting it affect
// identity. Where a provider requires a name argument it gets the asset ID, since
// changing a name is a replace on GCP and DigitalOcean.
func displayName(n *blockNode, p catalog.Provider, rt catalog.ResourceType, a model.Asset) {
	if p.NameArg != "" && !rt.OmitName && !declaresName(rt, p.NameArg) {
		n.add("", p.NameArg, quote(dashed(a.ID)))
	}
	if p.LabelArg != "" {
		n.add("", p.LabelArg, fmt.Sprintf("{ Name = %s }", quote(a.Name)))
	}
}

// declaresName reports whether a type already sets the name argument itself, in
// which case adding it again would be "Attribute redefined".
func declaresName(rt catalog.ResourceType, nameArg string) bool {
	for _, fx := range rt.Fixed {
		if fx.Block == "" && fx.Key == nameArg {
			return true
		}
	}
	return false
}

// staticAddress emits the durable address resource for an asset whose own address
// would otherwise change on restart, but only where the user asked for it.
func staticAddress(w *writer, p catalog.Provider, acc model.Account, a model.Asset, rt catalog.ResourceType) {
	if rt.StaticAddr == nil {
		return
	}
	if !staticEnabled(&a) {
		return
	}
	w.blank()
	w.line("# Durable address for %s, so rules referencing it do not go stale.", a.Name)
	switch p.Key {
	case "aws":
		w.block(fmt.Sprintf("resource %q %q", "aws_eip", a.ID), func() {
			w.arg("provider", "aws."+acc.ID)
			w.arg("domain", quote("vpc"))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_eip_association", a.ID), func() {
			w.arg("provider", "aws."+acc.ID)
			w.arg("instance_id", fmt.Sprintf("aws_instance.%s.id", a.ID))
			w.arg("allocation_id", fmt.Sprintf("aws_eip.%s.id", a.ID))
		})
	case "azure":
		w.block(fmt.Sprintf("resource %q %q", "azurerm_public_ip", a.ID), func() {
			w.arg("provider", "azurerm."+acc.ID)
			w.arg("name", quote(a.ID))
			w.arg("location", fmt.Sprintf("azurerm_resource_group.%s.location", acc.ID))
			w.arg("resource_group_name", fmt.Sprintf("azurerm_resource_group.%s.name", acc.ID))
			w.arg("allocation_method", quote("Static"))
		})
		w.line("# The machine's network interface references this.")
	case "gcp":
		w.block(fmt.Sprintf("resource %q %q", "google_compute_address", a.ID), func() {
			w.arg("provider", "google."+acc.ID)
			w.arg("name", quote(dashed(a.ID)))
			w.arg("region", "var."+acc.ID+"_region")
		})
		w.line("# The instance's access_config nat_ip references this.")
	}
}

// ruleOwner is the account whose firewall a rule belongs to: the account of the
// asset it attaches to.
func ruleOwner(f Flow, r fwRule) string {
	for _, e := range []Endpoint{f.From, f.To} {
		if e.Asset != nil && e.Asset.ID == r.Asset && e.Account != nil {
			return e.Account.ID
		}
	}
	return ""
}

// dashed converts an identifier to the lowercase hyphenated form GCP and
// DigitalOcean require for resource names.
func dashed(s string) string {
	return strings.ReplaceAll(strings.ToLower(s), "_", "-")
}
