package tofu

import (
	"fmt"
	"strings"

	"infrachart/internal/catalog"
	"infrachart/internal/model"
)

// Generate renders a chart as OpenTofu configuration, and returns the things the
// user must act on alongside it.
//
// Run model.Validate and model.Normalise first. Output is deterministic: every
// loop walks a slice in order, never a map.
func Generate(s model.Session) (string, []string) {
	report := Classify(s)
	w := &writer{}

	header(w)
	requiredProviders(w, s)

	// Rules are accumulated per account and rendered after the resources, because
	// DigitalOcean needs all of an asset's rules in one resource.
	firewalls := map[string]firewall{}
	for _, acc := range s.Accounts {
		if fw := newFirewall(acc.Provider); fw != nil {
			firewalls[acc.ID] = fw
		}
	}
	for _, f := range report.Flows {
		for _, o := range f.Outcomes {
			for _, r := range fwRulesFor(f, o) {
				owner := ruleOwner(f, r)
				if fw := firewalls[owner]; fw != nil {
					fw.add(r)
				}
			}
		}
	}

	guarded := guardedAssets(report)
	vars := newVarSet()

	for _, acc := range s.Accounts {
		p, ok := catalog.Get(acc.Provider)
		if !ok {
			continue
		}
		w.blank()
		w.line("# ---------------------------------------------------------------")
		w.line("# %s (%s)", acc.Name, p.Label)
		w.line("# ---------------------------------------------------------------")
		providerBlock(w, p, acc, vars)
		scaffold(w, acc.Provider, acc.ID)
		for _, a := range acc.Assets {
			assetResource(w, p, acc, a, guarded[a.ID], vars)
		}
		if fw := firewalls[acc.ID]; fw != nil {
			fw.render(w, acc.ID)
		}
	}

	if lists := prefixLists(report); len(lists) > 0 {
		w.blank()
		w.line("# Managed prefix lists, so a CDN can reach its origin without a CIDR.")
		for _, l := range lists {
			w.blank()
			w.block(fmt.Sprintf("data %q %q", "aws_ec2_managed_prefix_list", prefixListName(l)), func() {
				w.arg("name", quote(l))
			})
		}
	}

	vars.render(w)
	externalIPs(w, s)
	attachmentGaps(w, s, guarded)
	notes(w, report)

	return w.String(), report.Warnings()
}

func header(w *writer) {
	w.line("# Generated by infrachart. Review before applying.")
	w.line("#")
	w.line("# Resource bodies carry only the parameters the chart models. Run")
	w.line("# `tofu validate` to see what each provider still requires.")
	w.line("#")
	w.line("# Resource names come from asset IDs, never display names: a name-derived")
	w.line("# address would make renaming an asset destroy and recreate it.")
	w.line("#")
	w.line("# Removing an account also removes its provider block, and OpenTofu cannot")
	w.line("# destroy a resource whose provider is gone. Empty the account of assets,")
	w.line("# apply, then remove the account.")
	w.line("#")
	w.line("# Ports in these rules are always the DESTINATION port — the port being")
	w.line("# connected to. On AWS, from_port and to_port are the low and high bounds of")
	w.line("# one range, not a source and a destination: from_port = 443, to_port = 443")
	w.line("# is the range 443-443. Source ports are never constrained, because they are")
	w.line("# ephemeral, and every firewall here is stateful — return traffic needs no")
	w.line("# rule of its own.")
}

// requiredProviders declares only the providers the chart actually uses, so a
// chart with no Azure in it does not demand Azure credentials.
func requiredProviders(w *writer, s model.Session) {
	inUse := map[string]bool{}
	for _, acc := range s.Accounts {
		inUse[acc.Provider] = true
	}
	// catalog.All() is sorted by key, so the block is stable regardless of the
	// order accounts happen to appear in the chart.
	var used []catalog.Provider
	for _, p := range catalog.All() {
		if inUse[p.Key] {
			used = append(used, p)
		}
	}
	if len(used) == 0 {
		return
	}
	w.blank()
	w.block("terraform", func() {
		w.block("required_providers", func() {
			for _, p := range used {
				w.arg(p.TofuLocalName, fmt.Sprintf("{ source = %s }", quote(p.TofuSource)))
			}
		})
	})
}

// providerBlock gives each account its own aliased provider configuration. This is
// what lets one configuration span accounts and clouds, which in turn is what
// makes a cross-account reference both resolve the address and order the apply.
func providerBlock(w *writer, p catalog.Provider, acc model.Account, vars *varSet) {
	w.blank()
	w.line("# Credentials come from the environment or your provider profile.")
	node := &blockNode{}
	node.add("", "alias", quote(acc.ID))
	for _, fx := range p.Config {
		addFixed(node, fx, acc.ID, "")
	}
	w.block(fmt.Sprintf("provider %q", p.TofuLocalName), func() { node.render(w) })
	for _, v := range p.Variables {
		vars.add(varDecl{
			Name:        expand(v.Name, acc.ID, ""),
			Description: v.Description,
			Type:        v.Type,
			Default:     expand(v.Default, acc.ID, ""),
			Sensitive:   v.Sensitive,
		})
	}
	w.blank()
	w.block(fmt.Sprintf("variable %q", acc.ID+"_region"), func() {
		w.arg("description", quote("Region for "+acc.Name))
		w.arg("type", "string")
		w.arg("default", quote(defaultRegion(p.Key)))
	})
}

func defaultRegion(provider string) string {
	switch provider {
	case "aws":
		return "eu-west-2"
	case "azure":
		return "uksouth"
	case "gcp":
		return "europe-west2"
	}
	return "nyc3"
}

// scaffold emits the network each provider needs before anything can be attached
// to it. Minimal by design: a chart says nothing about subnetting.
func scaffold(w *writer, provider, accountID string) {
	local := accountID
	switch provider {
	case "aws":
		w.blank()
		w.block(fmt.Sprintf("data %q %q", "aws_availability_zones", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("state", quote("available"))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_vpc", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("cidr_block", quote("10.0.0.0/16"))
		})
		// Two subnets in different zones: a DB subnet group requires two, and so
		// does an application load balancer.
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_subnet", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("vpc_id", fmt.Sprintf("aws_vpc.%s.id", local))
			w.arg("cidr_block", quote("10.0.1.0/24"))
			w.arg("availability_zone", fmt.Sprintf("data.aws_availability_zones.%s.names[0]", local))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_subnet", local+"_b"), func() {
			w.arg("provider", "aws."+local)
			w.arg("vpc_id", fmt.Sprintf("aws_vpc.%s.id", local))
			w.arg("cidr_block", quote("10.0.2.0/24"))
			w.arg("availability_zone", fmt.Sprintf("data.aws_availability_zones.%s.names[1]", local))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_internet_gateway", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("vpc_id", fmt.Sprintf("aws_vpc.%s.id", local))
		})
	case "azure":
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "azurerm_resource_group", local), func() {
			w.arg("provider", "azurerm."+local)
			w.arg("name", quote(local))
			w.arg("location", "var."+local+"_region")
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "azurerm_virtual_network", local), func() {
			w.arg("provider", "azurerm."+local)
			w.arg("name", quote(local))
			w.arg("address_space", fmt.Sprintf("[%s]", quote("10.0.0.0/16")))
			w.arg("location", fmt.Sprintf("azurerm_resource_group.%s.location", local))
			w.arg("resource_group_name", fmt.Sprintf("azurerm_resource_group.%s.name", local))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "azurerm_subnet", local), func() {
			w.arg("provider", "azurerm."+local)
			w.arg("name", quote(local))
			w.arg("resource_group_name", fmt.Sprintf("azurerm_resource_group.%s.name", local))
			w.arg("virtual_network_name", fmt.Sprintf("azurerm_virtual_network.%s.name", local))
			w.arg("address_prefixes", fmt.Sprintf("[%s]", quote("10.0.1.0/24")))
		})
	case "gcp":
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "google_compute_network", local), func() {
			w.arg("provider", "google."+local)
			w.arg("name", quote(dashed(local)))
			w.arg("auto_create_subnetworks", "false")
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "google_compute_subnetwork", local), func() {
			w.arg("provider", "google."+local)
			w.arg("name", quote(dashed(local)))
			w.arg("ip_cidr_range", quote("10.0.1.0/24"))
			w.arg("region", "var."+local+"_region")
			w.arg("network", fmt.Sprintf("google_compute_network.%s.id", local))
		})
	case "digitalocean":
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "digitalocean_vpc", local), func() {
			w.arg("name", quote(dashed(local)))
			w.arg("region", "var."+local+"_region")
		})
	}
}

// assetResource emits one asset, its fixed arguments and its companions. The
// resource name is the asset ID; the display name goes into tags or labels, which
// providers update in place, so renaming an asset never replaces infrastructure.
func assetResource(w *writer, p catalog.Provider, acc model.Account, a model.Asset, guarded bool, vars *varSet) {
	rt, ok := catalog.Type(acc.Provider, a.Code)
	if !ok {
		return
	}

	// Arguments are collected by block path first, then rendered in one pass, so
	// a nested argument does not have to know where it sits in the output.
	root := &blockNode{}
	root.add("", "provider", p.TofuLocalName+"."+acc.ID)
	displayName(root, p, rt, a)

	// Arguments(), not Params: directives such as static_public_ip are not
	// arguments on any resource and would make the configuration invalid.
	for _, f := range rt.Arguments() {
		root.add(f.Block, f.Key, value(a.Params[f.ParamKey()]))
	}
	for _, fx := range rt.Fixed {
		addFixed(root, fx, acc.ID, a.ID)
	}
	// A companion the parent never references would be dead HCL.
	for _, c := range rt.Companions {
		if c.ParentRef != "" {
			root.add("", c.ParentRef, expand(c.ParentExpr, acc.ID, a.ID))
		}
	}
	if guarded {
		attach(root, acc, a, rt)
	}
	for _, v := range rt.Variables {
		vars.add(varDecl{
			Name:        expand(v.Name, acc.ID, a.ID),
			Description: v.Description,
			Type:        v.Type,
			Default:     expand(v.Default, acc.ID, a.ID),
			Sensitive:   v.Sensitive,
		})
	}

	w.blank()
	w.line("# %s → %s", acc.Name, a.Name)
	w.block(fmt.Sprintf("resource %q %q", rt.TofuType, a.ID), func() { root.render(w) })

	for _, c := range rt.Companions {
		companionResource(w, p, acc, a, c)
	}
	staticAddress(w, p, acc, a, rt)
}

// companionResource emits a resource an asset cannot exist without. Named
// <assetID>_<suffix> so it inherits the guarantee that renaming an asset never
// moves a resource address.
func companionResource(w *writer, p catalog.Provider, acc model.Account, a model.Asset, c catalog.Companion) {
	name := a.ID + "_" + c.Suffix
	node := &blockNode{}
	node.add("", "provider", p.TofuLocalName+"."+acc.ID)
	for _, fx := range c.Fixed {
		addFixed(node, fx, acc.ID, a.ID)
	}
	w.blank()
	w.line("# %s requires this", a.Name)
	w.block(fmt.Sprintf("resource %q %q", c.TofuType, name), func() { node.render(w) })
}

// guardedAssets is the set of assets that ended up with at least one firewall
// rule, and therefore need the rule attached to them.
func guardedAssets(r Report) map[string]bool {
	out := map[string]bool{}
	for _, f := range r.Flows {
		for _, o := range f.Outcomes {
			for _, rule := range fwRulesFor(f, o) {
				out[rule.Asset] = true
			}
		}
	}
	return out
}

// attach wires an asset to the firewall that protects it. Without this the rules
// exist but govern nothing — the output would look complete and do nothing.
//
// DigitalOcean needs no entry here: its firewall resource names the droplet
// directly, so attachment is inherent.
//
// Azure is handled in the firewall emitter instead: a security group attaches to a
// network interface there, not to the machine. attachmentGaps() still names every
// asset that nothing wires up, so the output never pretends to be complete.
func attach(n *blockNode, acc model.Account, a model.Asset, rt catalog.ResourceType) {
	sg := fmt.Sprintf("[aws_security_group.%s.id]", a.ID)
	switch rt.TofuType {
	case "aws_instance", "aws_db_instance":
		n.add("", "vpc_security_group_ids", sg)
	case "aws_lb":
		n.add("", "security_groups", sg)
	case "aws_ecs_service":
		// A Fargate service takes its security groups inside the network block.
		n.add("network_configuration", "security_groups", sg)
	case "google_compute_instance":
		// GCP firewall rules select instances by network tag rather than by group.
		n.add("", "tags", fmt.Sprintf("[%s]", quote(gcpTag(a.ID))))
	}
}

// displayName records the chart's label on the resource without letting it affect
// identity. Where a provider requires a name argument it gets the asset ID, since
// changing a name is a replace on GCP and DigitalOcean.
func displayName(n *blockNode, p catalog.Provider, rt catalog.ResourceType, a model.Asset) {
	if p.NameArg != "" && !rt.OmitName && !declaresName(rt, p.NameArg) {
		n.add("", p.NameArg, quote(dashed(a.ID)))
	}
	if p.LabelArg != "" {
		n.add("", p.LabelArg, fmt.Sprintf("{ Name = %s }", quote(a.Name)))
	}
}

// declaresName reports whether a type already sets the name argument itself, in
// which case adding it again would be "Attribute redefined".
func declaresName(rt catalog.ResourceType, nameArg string) bool {
	for _, fx := range rt.Fixed {
		if fx.Block == "" && fx.Key == nameArg {
			return true
		}
	}
	return false
}

// staticAddress emits the durable address resource for an asset whose own address
// would otherwise change on restart, but only where the user asked for it.
func staticAddress(w *writer, p catalog.Provider, acc model.Account, a model.Asset, rt catalog.ResourceType) {
	if rt.StaticAddr == nil {
		return
	}
	if on, _ := a.Params[catalog.ParamStaticPublicIP].(bool); !on {
		return
	}
	w.blank()
	w.line("# Durable address for %s, so rules referencing it do not go stale.", a.Name)
	switch p.Key {
	case "aws":
		w.block(fmt.Sprintf("resource %q %q", "aws_eip", a.ID), func() {
			w.arg("provider", "aws."+acc.ID)
			w.arg("domain", quote("vpc"))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_eip_association", a.ID), func() {
			w.arg("provider", "aws."+acc.ID)
			w.arg("instance_id", fmt.Sprintf("aws_instance.%s.id", a.ID))
			w.arg("allocation_id", fmt.Sprintf("aws_eip.%s.id", a.ID))
		})
	case "azure":
		w.block(fmt.Sprintf("resource %q %q", "azurerm_public_ip", a.ID), func() {
			w.arg("provider", "azurerm."+acc.ID)
			w.arg("name", quote(a.ID))
			w.arg("location", fmt.Sprintf("azurerm_resource_group.%s.location", acc.ID))
			w.arg("resource_group_name", fmt.Sprintf("azurerm_resource_group.%s.name", acc.ID))
			w.arg("allocation_method", quote("Static"))
		})
		w.line("# Attach this to the machine's network interface.")
	case "gcp":
		w.block(fmt.Sprintf("resource %q %q", "google_compute_address", a.ID), func() {
			w.arg("provider", "google."+acc.ID)
			w.arg("name", quote(dashed(a.ID)))
			w.arg("region", "var."+acc.ID+"_region")
		})
		w.line("# Reference this from the instance's access_config nat_ip.")
	}
}

// externalIPs records the hardcoded addresses a chart uses. Nothing is created for
// them — they only supply a CIDR to the rules above.
func externalIPs(w *writer, s model.Session) {
	if len(s.ExternalIPs) == 0 {
		return
	}
	w.blank()
	w.line("# Hardcoded addresses. Not managed here — their CIDRs appear in the rules above.")
	for _, e := range s.ExternalIPs {
		w.line("#   %s — %s", e.Label, e.IP)
	}
}

// notes records the connections that produced no rule, in the file itself. Someone
// reading the configuration later has no access to the UI warnings.
func notes(w *writer, r Report) {
	var lines []string
	for _, f := range r.Flows {
		for _, o := range f.Outcomes {
			if o.Strategy == StratCIDR || o.Strategy == StratSecurityGroupRef || o.Strategy == StratEdgeNative {
				continue
			}
			lines = append(lines, fmt.Sprintf("#   %s → %s (%s/%s): %s",
				f.From.Label, f.To.Label, o.Rule.Protocol, portOrAny(o.Rule.Port), o.Reason))
		}
	}
	if len(lines) == 0 {
		return
	}
	w.blank()
	w.line("# Declared connections that produced no firewall rule:")
	for _, l := range lines {
		w.line("%s", l)
	}
}

func portOrAny(p string) string {
	if p == "" {
		return "(unset)"
	}
	return p
}

// ruleOwner is the account whose firewall a rule belongs to: the account of the
// asset it attaches to.
func ruleOwner(f Flow, r fwRule) string {
	for _, e := range []Endpoint{f.From, f.To} {
		if e.Asset != nil && e.Asset.ID == r.Asset && e.Account != nil {
			return e.Account.ID
		}
	}
	return ""
}

// dashed converts an identifier to the lowercase hyphenated form GCP and
// DigitalOcean require for resource names.
func dashed(s string) string {
	return strings.ReplaceAll(strings.ToLower(s), "_", "-")
}

// attachmentGaps lists assets whose firewall could not be wired to them here.
// Azure attaches a security group to a network interface or a subnet, and a chart
// does not describe either, so those associations are left to the user.
func attachmentGaps(w *writer, s model.Session, guarded map[string]bool) {
	var lines []string
	for _, acc := range s.Accounts {
		for _, a := range acc.Assets {
			if !guarded[a.ID] {
				continue
			}
			rt, ok := catalog.Type(acc.Provider, a.Code)
			if !ok {
				continue
			}
			switch rt.TofuType {
			case "aws_instance", "aws_db_instance", "aws_lb", "aws_ecs_service",
				"google_compute_instance", "digitalocean_droplet",
				"azurerm_linux_virtual_machine":
				continue
			}
			lines = append(lines, fmt.Sprintf("#   %s (%s) — attach its firewall yourself", a.Name, rt.TofuType))
		}
	}
	if len(lines) == 0 {
		return
	}
	w.blank()
	w.line("# Rules were generated for these, but nothing here attaches them:")
	for _, l := range lines {
		w.line("%s", l)
	}
}
