package tofu

import (
	"fmt"
	"strings"

	"infrachart/internal/catalog"
	"infrachart/internal/model"
)

// Generate renders a chart as OpenTofu configuration, and returns the things the
// user must act on alongside it.
//
// Run model.Validate and model.Normalise first. Output is deterministic: every
// loop walks a slice in order, never a map.
func Generate(s model.Session) (string, []string) {
	report := Classify(s)
	w := &writer{}

	header(w)
	requiredProviders(w, s, featureProviders(s))

	// Rules are accumulated per account and rendered after the resources, because
	// DigitalOcean needs all of an asset's rules in one resource.
	firewalls := map[string]firewall{}
	for _, acc := range s.Accounts {
		if fw := newFirewall(acc.Provider); fw != nil {
			firewalls[acc.ID] = fw
		}
	}
	for _, k := range dedupeRules(report, firewalls) {
		firewalls[k.owner].add(k.rule)
	}

	guarded := guardedAssets(report)
	vars := newVarSet()
	renderKeyLocals(w, s)
	// The key variables exist only where something references them, so a chart
	// with no SSH key wiring is not asked for a key it has no use for.
	for _, acc := range s.Accounts {
		for _, a := range acc.Assets {
			rt, ok := catalog.Type(acc.Provider, a.Code)
			if !ok || !usesSSHKey(rt, a) {
				continue
			}
			for _, d := range sshKeyVars(acc.ID, acc.Name) {
				vars.add(d)
			}
		}
	}

	for _, acc := range s.Accounts {
		p, ok := catalog.Get(acc.Provider)
		if !ok {
			continue
		}
		w.blank()
		w.line("# ---------------------------------------------------------------")
		w.line("# %s (%s)", acc.Name, p.Label)
		w.line("# ---------------------------------------------------------------")
		providerBlock(w, p, acc, vars)
		scaffold(w, acc.Provider, acc.ID)
		for _, a := range acc.Assets {
			assetResource(w, p, acc, a, guarded[a.ID], vars)
		}
		if fw := firewalls[acc.ID]; fw != nil {
			fw.render(w, acc.ID)
		}
	}

	if lists := prefixLists(report); len(lists) > 0 {
		w.blank()
		w.line("# Managed prefix lists, so a CDN can reach its origin without a CIDR.")
		for _, l := range lists {
			w.blank()
			w.block(fmt.Sprintf("data %q %q", "aws_ec2_managed_prefix_list", prefixListName(l)), func() {
				w.arg("name", quote(l))
			})
		}
	}

	if needsLocal := renderInventory(w, s); needsLocal != (len(featureProviders(s)) > 0) {
		// A local_file with no provider declared, or the reverse. Both are broken,
		// and they are computed from the same source so they cannot disagree.
		panic("inventory and its provider requirement disagree")
	}

	vars.render(w)
	externalIPs(w, s)
	attachmentGaps(w, s, guarded)
	notes(w, report)

	warnings := append(report.Warnings(), ansibleWarnings(s, report)...)
	warnings = append(warnings, unreachableWarnings(report)...)
	return w.String(), append(warnings, blankChoiceWarnings(s)...)
}

func header(w *writer) {
	w.line("# Generated by infrachart. Review before applying.")
	w.line("#")
	w.line("# Resource bodies carry only the parameters the chart models. Run")
	w.line("# `tofu validate` to see what each provider still requires.")
	w.line("#")
	w.line("# Resource names come from asset IDs, never display names: a name-derived")
	w.line("# address would make renaming an asset destroy and recreate it.")
	w.line("#")
	w.line("# Removing an account also removes its provider block, and OpenTofu cannot")
	w.line("# destroy a resource whose provider is gone. Empty the account of assets,")
	w.line("# apply, then remove the account.")
	w.line("#")
	w.line("# Ports in these rules are always the DESTINATION port — the port being")
	w.line("# connected to. On AWS, from_port and to_port are the low and high bounds of")
	w.line("# one range, not a source and a destination: from_port = 443, to_port = 443")
	w.line("# is the range 443-443. Source ports are never constrained, because they are")
	w.line("# ephemeral, and every firewall here is stateful — return traffic needs no")
	w.line("# rule of its own.")
}

// requiredProviders declares only the providers the chart actually uses, so a
// chart with no Azure in it does not demand Azure credentials.
// featureProviders are providers a chart never mentions but a feature needs. The
// inventory is a local_file, so an Ansible chart requires hashicorp/local even
// though no account is a "local" account.
func featureProviders(s model.Session) []catalog.Provider {
	if groups, _ := inventory(s); len(groups) == 0 {
		return nil
	}
	return []catalog.Provider{{
		Key: "local", Label: "Local", TofuLocalName: "local", TofuSource: "hashicorp/local",
	}}
}

func requiredProviders(w *writer, s model.Session, extra []catalog.Provider) {
	inUse := map[string]bool{}
	for _, acc := range s.Accounts {
		inUse[acc.Provider] = true
	}
	// catalog.All() is sorted by key, so the block is stable regardless of the
	// order accounts happen to appear in the chart.
	var used []catalog.Provider
	for _, p := range catalog.All() {
		if inUse[p.Key] {
			used = append(used, p)
		}
	}
	used = append(used, extra...)
	if len(used) == 0 {
		return
	}
	w.blank()
	w.block("terraform", func() {
		w.block("required_providers", func() {
			for _, p := range used {
				w.arg(p.TofuLocalName, fmt.Sprintf("{ source = %s }", quote(p.TofuSource)))
			}
		})
	})
}

// providerBlock gives each account its own aliased provider configuration. This is
// what lets one configuration span accounts and clouds, which in turn is what
// makes a cross-account reference both resolve the address and order the apply.
func providerBlock(w *writer, p catalog.Provider, acc model.Account, vars *varSet) {
	w.blank()
	w.line("# Credentials come from the environment or your provider profile.")
	ctx := exprCtx{accountID: acc.ID}
	node := &blockNode{}
	node.add("", "alias", quote(acc.ID))
	for _, fx := range p.Config {
		addFixed(node, fx, ctx)
	}
	w.block(fmt.Sprintf("provider %q", p.TofuLocalName), func() { node.render(w) })
	for _, v := range p.Variables {
		vars.add(varDecl{
			Name:        expand(v.Name, ctx),
			Description: v.Description,
			Type:        v.Type,
			Default:     expand(v.Default, ctx),
			Sensitive:   v.Sensitive,
		})
	}
	w.blank()
	// The variable stays even though the chart now supplies a value, so a region
	// can still be overridden per apply with TF_VAR without editing the chart.
	w.block(fmt.Sprintf("variable %q", acc.ID+"_region"), func() {
		w.arg("description", quote("Region for "+acc.Name))
		w.arg("type", "string")
		w.arg("default", quote(p.Region(acc.Params)))
	})
}

// scaffold emits the network each provider needs before anything can be attached
// to it. Minimal by design: a chart says nothing about subnetting.
func scaffold(w *writer, provider, accountID string) {
	local := accountID
	switch provider {
	case "aws":
		w.blank()
		w.block(fmt.Sprintf("data %q %q", "aws_availability_zones", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("state", quote("available"))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_vpc", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("cidr_block", quote("10.0.0.0/16"))
		})
		// Two subnets in different zones: a DB subnet group requires two, and so
		// does an application load balancer.
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_subnet", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("vpc_id", fmt.Sprintf("aws_vpc.%s.id", local))
			w.arg("cidr_block", quote("10.0.1.0/24"))
			w.arg("availability_zone", fmt.Sprintf("data.aws_availability_zones.%s.names[0]", local))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_subnet", local+"_b"), func() {
			w.arg("provider", "aws."+local)
			w.arg("vpc_id", fmt.Sprintf("aws_vpc.%s.id", local))
			w.arg("cidr_block", quote("10.0.2.0/24"))
			w.arg("availability_zone", fmt.Sprintf("data.aws_availability_zones.%s.names[1]", local))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_internet_gateway", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("vpc_id", fmt.Sprintf("aws_vpc.%s.id", local))
		})
		// A gateway with nothing routed to it is a gateway that does nothing. Without
		// this table both subnets are private: an instance can hold a public IP and
		// allow port 22 and still be unreachable, because the reply has no way out.
		//
		// An inline route rather than a separate aws_route resource: one resource
		// instead of two, and the inline form is authoritative, so nothing can add a
		// route behind the chart's back.
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_route_table", local), func() {
			w.arg("provider", "aws."+local)
			w.arg("vpc_id", fmt.Sprintf("aws_vpc.%s.id", local))
			w.block("route", func() {
				w.arg("cidr_block", quote("0.0.0.0/0"))
				w.arg("gateway_id", fmt.Sprintf("aws_internet_gateway.%s.id", local))
			})
		})
		// Both subnets, because an asset may land in either and a load balancer
		// spans both. A subnet left unassociated falls back to the VPC's main route
		// table, which has no gateway route — reachable or not by accident.
		for _, subnet := range []string{local, local + "_b"} {
			w.blank()
			w.block(fmt.Sprintf("resource %q %q", "aws_route_table_association", subnet), func() {
				w.arg("provider", "aws."+local)
				w.arg("subnet_id", fmt.Sprintf("aws_subnet.%s.id", subnet))
				w.arg("route_table_id", fmt.Sprintf("aws_route_table.%s.id", local))
			})
		}
	case "azure":
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "azurerm_resource_group", local), func() {
			w.arg("provider", "azurerm."+local)
			w.arg("name", quote(local))
			w.arg("location", "var."+local+"_region")
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "azurerm_virtual_network", local), func() {
			w.arg("provider", "azurerm."+local)
			w.arg("name", quote(local))
			w.arg("address_space", fmt.Sprintf("[%s]", quote("10.0.0.0/16")))
			w.arg("location", fmt.Sprintf("azurerm_resource_group.%s.location", local))
			w.arg("resource_group_name", fmt.Sprintf("azurerm_resource_group.%s.name", local))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "azurerm_subnet", local), func() {
			w.arg("provider", "azurerm."+local)
			w.arg("name", quote(local))
			w.arg("resource_group_name", fmt.Sprintf("azurerm_resource_group.%s.name", local))
			w.arg("virtual_network_name", fmt.Sprintf("azurerm_virtual_network.%s.name", local))
			w.arg("address_prefixes", fmt.Sprintf("[%s]", quote("10.0.1.0/24")))
		})
	case "gcp":
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "google_compute_network", local), func() {
			w.arg("provider", "google."+local)
			w.arg("name", quote(dashed(local)))
			w.arg("auto_create_subnetworks", "false")
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "google_compute_subnetwork", local), func() {
			w.arg("provider", "google."+local)
			w.arg("name", quote(dashed(local)))
			w.arg("ip_cidr_range", quote("10.0.1.0/24"))
			w.arg("region", "var."+local+"_region")
			w.arg("network", fmt.Sprintf("google_compute_network.%s.id", local))
		})
	case "digitalocean":
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "digitalocean_vpc", local), func() {
			w.arg("name", quote(dashed(local)))
			w.arg("region", "var."+local+"_region")
		})
	}
}

// assetResource emits one asset, its fixed arguments and its companions. The
// resource name is the asset ID; the display name goes into tags or labels, which
// providers update in place, so renaming an asset never replaces infrastructure.
func assetResource(w *writer, p catalog.Provider, acc model.Account, a model.Asset, guarded bool, vars *varSet) {
	rt, ok := catalog.Type(acc.Provider, a.Code)
	if !ok {
		return
	}

	// Arguments are collected by block path first, then rendered in one pass, so
	// a nested argument does not have to know where it sits in the output.
	ctx := assetCtx(acc, a)
	root := &blockNode{}
	root.add("", "provider", p.TofuLocalName+"."+acc.ID)
	displayName(root, p, rt, a)

	// Arguments(), not Params: directives such as static_public_ip are not
	// arguments on any resource and would make the configuration invalid.
	for _, f := range rt.Arguments() {
		// Same gate as Fixed and Companions below. An argument in a block the
		// resource does not accept is a plan error, not a harmless extra.
		if !required(f.RequiresParam, f.RequiresValue, a) {
			continue
		}
		v := a.Params[f.ParamKey()]
		// An unwritten script is absence, not an empty script. Emitting it would
		// produce user_data = "" and, worse, base64encode("") on Azure.
		if f.Type == catalog.FieldScript && v == "" {
			continue
		}
		root.add(f.Block, f.Key, wrapped(f, v))
	}
	for _, fx := range rt.Fixed {
		if !required(fx.RequiresParam, fx.RequiresValue, a) {
			continue
		}
		addFixed(root, fx, ctx)
	}
	// A companion the parent never references would be dead HCL.
	for _, c := range rt.Companions {
		if !required(c.RequiresParam, c.RequiresValue, a) {
			continue
		}
		if c.ParentRef != "" {
			root.add("", c.ParentRef, expand(c.ParentExpr, ctx))
		}
	}
	if ansibleOn(&a) {
		keyPrecondition(root, acc, &a)
	}
	if guarded {
		attach(root, acc, a, rt)
	}
	for _, v := range rt.Variables {
		vars.add(varDecl{
			Name:        expand(v.Name, ctx),
			Description: v.Description,
			Type:        v.Type,
			Default:     expand(v.Default, ctx),
			Sensitive:   v.Sensitive,
		})
	}

	w.blank()
	w.line("# %s → %s", acc.Name, a.Name)
	w.block(fmt.Sprintf("resource %q %q", rt.TofuType, a.ID), func() { root.render(w) })

	for _, c := range rt.Companions {
		if !required(c.RequiresParam, c.RequiresValue, a) {
			continue
		}
		companionResource(w, p, acc, a, c)
	}
	staticAddress(w, p, acc, a, rt)
}

// companionResource emits a resource an asset cannot exist without. Named
// <assetID>_<suffix> so it inherits the guarantee that renaming an asset never
// moves a resource address.
func companionResource(w *writer, p catalog.Provider, acc model.Account, a model.Asset, c catalog.Companion) {
	name := a.ID + "_" + c.Suffix
	ctx := assetCtx(acc, a)
	node := &blockNode{}
	// count first: it is a meta-argument and reads as one at the top of the block.
	if c.Count != "" {
		node.add("", "count", expand(c.Count, ctx))
	}
	node.add("", "provider", p.TofuLocalName+"."+acc.ID)
	for _, fx := range c.Fixed {
		// Same gate as an asset's own fixed arguments. Without it a conditional
		// argument inside a companion was emitted unconditionally — which is how
		// Azure's public IP came out allocated but never attached.
		if !required(fx.RequiresParam, fx.RequiresValue, a) {
			continue
		}
		addFixed(node, fx, ctx)
	}
	w.blank()
	kind := "resource"
	if c.Data {
		// A data source is looked up, not created, so "requires this" would misread
		// as something the apply brings into existence.
		kind = "data"
		w.line("# %s resolves its image here, so the id is right for the account's region", a.Name)
	} else {
		w.line("# %s requires this", a.Name)
	}
	w.block(fmt.Sprintf("%s %q %q", kind, c.TofuType, name), func() { node.render(w) })
}

// assetCtx is what a catalog expression may refer to for one asset.
func assetCtx(acc model.Account, a model.Asset) exprCtx {
	return exprCtx{
		accountID: acc.ID,
		assetID:   a.ID,
		sshKey:    sshKeyLocal(a.ID),
		sshUser:   loginUser(&a),
	}
}

// ownedRule is one firewall rule and the account whose firewall carries it.
type ownedRule struct {
	owner string
	rule  fwRule
}

// dedupeRules collapses rules that describe the same permission.
//
// Two connections can mean the same thing — a host reaching the internet on 443,
// and reaching something that resolves to the same address on the same port — and
// so can one connection carrying a rule twice. Every provider funnels through
// here, so this is the one place that has to know.
//
// It is not a tidiness pass. AWS rejects the second identical rule outright with
// InvalidPermission.Duplicate, which fails the apply after some of the chart has
// already been created. `tofu validate` cannot see it, because the two resources
// are perfectly valid on their own and only collide at the API.
//
// Everything but the comment is the rule's identity; the comments are joined, so
// the output still says why a merged rule exists rather than silently naming one
// reason out of two.
func dedupeRules(report Report, firewalls map[string]firewall) []ownedRule {
	seen := map[ownedRule]int{}
	var out []ownedRule
	for _, f := range report.Flows {
		for _, o := range f.Outcomes {
			for _, r := range fwRulesFor(f, o) {
				owner := ruleOwner(f, r)
				if fw := firewalls[owner]; fw == nil {
					continue
				}
				key := ownedRule{owner, r}
				key.rule.Comment = ""
				if i, ok := seen[key]; ok {
					out[i].rule.Comment = mergeComments(out[i].rule.Comment, r.Comment)
					continue
				}
				seen[key] = len(out)
				out = append(out, ownedRule{owner, r})
			}
		}
	}
	return out
}

// mergeComments joins the reasons for a merged rule, dropping a repeat rather than
// saying the same thing twice.
func mergeComments(existing, add string) string {
	if add == "" || existing == add || strings.Contains(existing, add) {
		return existing
	}
	if existing == "" {
		return add
	}
	return existing + "; also " + add
}

// required reports whether a conditional Fixed, Companion or ParamField applies.
//
// An empty param always applies. With a value, the named directive must equal it,
// which is how several companions share one select and only the chosen one is
// emitted. Without, the directive is a boolean that must be on.
func required(param, value string, a model.Asset) bool {
	if param == "" {
		return true
	}
	if value != "" {
		got, _ := a.Params[param].(string)
		return got == value
	}
	on, _ := a.Params[param].(bool)
	return on
}

// wrapped renders a param value, applying the type's Wrap expression when it has
// one. Azure's custom_data is the reason: it takes base64 where every other cloud
// takes a plain string.
func wrapped(f catalog.ParamField, v any) string {
	rendered := value(v)
	if f.Wrap == "" {
		return rendered
	}
	return fmt.Sprintf(f.Wrap, rendered)
}

// guardedAssets is the set of assets that ended up with at least one firewall
// rule, and therefore need the rule attached to them.
func guardedAssets(r Report) map[string]bool {
	out := map[string]bool{}
	for _, f := range r.Flows {
		for _, o := range f.Outcomes {
			for _, rule := range fwRulesFor(f, o) {
				out[rule.Asset] = true
			}
		}
	}
	return out
}

// attach wires an asset to the firewall that protects it. Without this the rules
// exist but govern nothing — the output would look complete and do nothing.
//
// DigitalOcean needs no entry here: its firewall resource names the droplet
// directly, so attachment is inherent.
//
// Azure is handled in the firewall emitter instead: a security group attaches to a
// network interface there, not to the machine. attachmentGaps() still names every
// asset that nothing wires up, so the output never pretends to be complete.
func attach(n *blockNode, acc model.Account, a model.Asset, rt catalog.ResourceType) {
	sg := fmt.Sprintf("[aws_security_group.%s.id]", a.ID)
	switch rt.TofuType {
	case "aws_instance", "aws_db_instance":
		n.add("", "vpc_security_group_ids", sg)
	case "aws_lb":
		n.add("", "security_groups", sg)
	case "aws_ecs_service":
		// A Fargate service takes its security groups inside the network block.
		n.add("network_configuration", "security_groups", sg)
	case "google_compute_instance":
		// GCP firewall rules select instances by network tag rather than by group.
		n.add("", "tags", fmt.Sprintf("[%s]", quote(gcpTag(a.ID))))
	}
}

// displayName records the chart's label on the resource without letting it affect
// identity. Where a provider requires a name argument it gets the asset ID, since
// changing a name is a replace on GCP and DigitalOcean.
func displayName(n *blockNode, p catalog.Provider, rt catalog.ResourceType, a model.Asset) {
	if p.NameArg != "" && !rt.OmitName && !declaresName(rt, p.NameArg) {
		n.add("", p.NameArg, quote(dashed(a.ID)))
	}
	if p.LabelArg != "" {
		n.add("", p.LabelArg, fmt.Sprintf("{ Name = %s }", quote(a.Name)))
	}
}

// declaresName reports whether a type already sets the name argument itself, in
// which case adding it again would be "Attribute redefined".
func declaresName(rt catalog.ResourceType, nameArg string) bool {
	for _, fx := range rt.Fixed {
		if fx.Block == "" && fx.Key == nameArg {
			return true
		}
	}
	return false
}

// staticAddress emits the durable address resource for an asset whose own address
// would otherwise change on restart, but only where the user asked for it.
func staticAddress(w *writer, p catalog.Provider, acc model.Account, a model.Asset, rt catalog.ResourceType) {
	if rt.StaticAddr == nil {
		return
	}
	if on, _ := a.Params[catalog.ParamStaticPublicIP].(bool); !on {
		return
	}
	w.blank()
	w.line("# Durable address for %s, so rules referencing it do not go stale.", a.Name)
	switch p.Key {
	case "aws":
		w.block(fmt.Sprintf("resource %q %q", "aws_eip", a.ID), func() {
			w.arg("provider", "aws."+acc.ID)
			w.arg("domain", quote("vpc"))
		})
		w.blank()
		w.block(fmt.Sprintf("resource %q %q", "aws_eip_association", a.ID), func() {
			w.arg("provider", "aws."+acc.ID)
			w.arg("instance_id", fmt.Sprintf("aws_instance.%s.id", a.ID))
			w.arg("allocation_id", fmt.Sprintf("aws_eip.%s.id", a.ID))
		})
	case "azure":
		w.block(fmt.Sprintf("resource %q %q", "azurerm_public_ip", a.ID), func() {
			w.arg("provider", "azurerm."+acc.ID)
			w.arg("name", quote(a.ID))
			w.arg("location", fmt.Sprintf("azurerm_resource_group.%s.location", acc.ID))
			w.arg("resource_group_name", fmt.Sprintf("azurerm_resource_group.%s.name", acc.ID))
			w.arg("allocation_method", quote("Static"))
		})
		w.line("# The machine's network interface references this.")
	case "gcp":
		w.block(fmt.Sprintf("resource %q %q", "google_compute_address", a.ID), func() {
			w.arg("provider", "google."+acc.ID)
			w.arg("name", quote(dashed(a.ID)))
			w.arg("region", "var."+acc.ID+"_region")
		})
		w.line("# The instance's access_config nat_ip references this.")
	}
}

// externalIPs records the hardcoded addresses a chart uses. Nothing is created for
// them — they only supply a CIDR to the rules above.
func externalIPs(w *writer, s model.Session) {
	if len(s.ExternalIPs) == 0 {
		return
	}
	w.blank()
	w.line("# Hardcoded addresses. Not managed here — their CIDRs appear in the rules above.")
	for _, e := range s.ExternalIPs {
		w.line("#   %s — %s", e.Label, e.IP)
	}
}

// notes records the connections that produced no rule, in the file itself. Someone
// reading the configuration later has no access to the UI warnings.
func notes(w *writer, r Report) {
	var lines []string
	for _, f := range r.Flows {
		for _, o := range f.Outcomes {
			if o.Strategy == StratCIDR || o.Strategy == StratSecurityGroupRef || o.Strategy == StratEdgeNative {
				continue
			}
			lines = append(lines, fmt.Sprintf("#   %s → %s (%s/%s): %s",
				f.From.Label, f.To.Label, o.Rule.Protocol, portOrAny(o.Rule.Port), o.Reason))
		}
	}
	if len(lines) == 0 {
		return
	}
	w.blank()
	w.line("# Declared connections that produced no firewall rule:")
	for _, l := range lines {
		w.line("%s", l)
	}
}

func portOrAny(p string) string {
	if p == "" {
		return "(unset)"
	}
	return p
}

// ruleOwner is the account whose firewall a rule belongs to: the account of the
// asset it attaches to.
func ruleOwner(f Flow, r fwRule) string {
	for _, e := range []Endpoint{f.From, f.To} {
		if e.Asset != nil && e.Asset.ID == r.Asset && e.Account != nil {
			return e.Account.ID
		}
	}
	return ""
}

// dashed converts an identifier to the lowercase hyphenated form GCP and
// DigitalOcean require for resource names.
func dashed(s string) string {
	return strings.ReplaceAll(strings.ToLower(s), "_", "-")
}

// attachmentGaps lists assets whose firewall could not be wired to them here.
// Azure attaches a security group to a network interface or a subnet, and a chart
// does not describe either, so those associations are left to the user.
func attachmentGaps(w *writer, s model.Session, guarded map[string]bool) {
	var lines []string
	for _, acc := range s.Accounts {
		for _, a := range acc.Assets {
			if !guarded[a.ID] {
				continue
			}
			rt, ok := catalog.Type(acc.Provider, a.Code)
			if !ok {
				continue
			}
			switch rt.TofuType {
			case "aws_instance", "aws_db_instance", "aws_lb", "aws_ecs_service",
				"google_compute_instance", "digitalocean_droplet",
				"azurerm_linux_virtual_machine":
				continue
			}
			lines = append(lines, fmt.Sprintf("#   %s (%s) — attach its firewall yourself", a.Name, rt.TofuType))
		}
	}
	if len(lines) == 0 {
		return
	}
	w.blank()
	w.line("# Rules were generated for these, but nothing here attaches them:")
	for _, l := range lines {
		w.line("%s", l)
	}
}

// blankChoiceWarnings reports a field the chart opted into and then left empty.
//
// Choosing "Custom AMI ID" and typing nothing is the case this exists for: it
// reaches generation as ami = "", a resource that looks complete and cannot
// launch. Blank is accepted while editing so the drawer still renders, then
// refused here — the same treatment a blank port gets.
//
// The rule is deliberately about the gate rather than about any particular field.
// An ungated field left blank is absence, and has a default behind it; a gated one
// is a question the user chose to be asked and did not answer.
func blankChoiceWarnings(s model.Session) []string {
	var out []string
	for _, acc := range s.Accounts {
		for _, a := range acc.Assets {
			rt, ok := catalog.Type(acc.Provider, a.Code)
			if !ok {
				continue
			}
			for _, f := range rt.Arguments() {
				if f.RequiresValue == "" || !required(f.RequiresParam, f.RequiresValue, a) {
					continue
				}
				v, isText := a.Params[f.ParamKey()].(string)
				if !isText || strings.TrimSpace(v) != "" {
					continue
				}
				out = append(out, fmt.Sprintf(
					"%s → %s chose %q but left %s empty — enter a value, or pick a different option",
					acc.Name, a.Name, f.RequiresValue, f.Label))
			}
		}
	}
	return out
}

// unreachableWarnings reports an asset that is allowed inbound from outside its
// own network but has no address anything out there could reach.
//
// A firewall rule permits traffic; it does not deliver it. An instance with no
// public address and a rule allowing port 22 generates cleanly, applies cleanly,
// and cannot be connected to — the failure looks like a firewall problem and is
// not one.
//
// Only traffic from outside the account needs a public address. A same-account
// peer resolves to a security group reference over private addressing, so
// warning about it would be a false alarm on the most common case of all.
func unreachableWarnings(r Report) []string {
	var out []string
	for _, f := range r.Flows {
		if f.To.Asset == nil || f.To.Account == nil || f.To.Type.Network != catalog.NetFirewalled {
			continue
		}
		// The internet and a hardcoded address are outside by definition; an asset
		// is outside when it sits in another account, because the two VPCs have no
		// private path between them.
		external := f.From.Ref.Type != model.NodeAsset ||
			f.From.Account == nil || f.From.Account.ID != f.To.Account.ID
		if !external {
			continue
		}
		// A refused outcome emits nothing, so it grants no access to warn about.
		grants := false
		for _, o := range f.Outcomes {
			if o.Strategy != StratRefused {
				grants = true
				break
			}
		}
		if !grants {
			continue
		}
		if reason := noPublicAddress(f.To.Type, f.To.Asset); reason != "" {
			out = append(out, fmt.Sprintf("%s → %s is allowed inbound from %s, but %s",
				f.To.Account.Name, f.To.Asset.Name, f.From.Label, reason))
		}
	}
	return out
}
